name: Release APP

# Trigger the workflow on push but only for the master branch
on:
  push:
    branches:
      - main
    types: [closed]

jobs:
  build-test-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.15.1"
      - run: npm install
      - run: npm run build
#      - run: npm test
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}