name: Pull Request Check

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.15.1"
      - run: npm install
      - run: npm run-script lint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}